### ISSUE TITLE
Add SeleneSelect or anolog

### ISSUE THREAD

**Issue by SergeyPirogov** [yashaka/selene#112]
Now it's a big ugly to use Select element with Selene

```
select = Select(s(by.model("operator")).get_actual_webelement())
select.select_by_visible_text("/")
```

Need to add Selene wrapper over Selenium Select to be able to write:

```
s("locator").select_by_value("vaue")

s("locator").select_by_visible_text("/")
```

**Comment by yashaka** [comment]
it should work like this:

Select(s(by.model("operator"))).select_by_visible_text("/")

I believe it's not ugly:)
It's not laconic, but it's KISS:)
SeleneElement - is "general element". It should provide operations common
for all elements
If we will add more "context specific" operations it will become a mess,
not a SeleneElement but SeleneDropdownRadioGroupBoxSuperPuperElement. It's
not OOP. It breaks Single Responsibility principle, it also has "Big Class
Smell"...

Moreover, rather often we have some custom implementation of Dropdowns,
etc....
So we nevertheless might create our own dropdown, something like:

class SelectList(object):
def __init__(self, element):
# type: (SeleneElement) -> None
self._element = element
def open(self):
self._element.click()
def _options(self):
return self._element.all('option')
def select_by_value(self, value):
self._options().element_by(have.value(value)).click()
def select_by_text(self, text):
self._options().element_by(have.text(text)).click()
def select_by_exact_text(self, text):
self._options().element_by(have.exact_text(text)).click()
def set(self, value):
self.open()
self.select_by_value(value)

And use it like:

sex = SelectList(s('#sex'))
sex.select_by_text('male')

or just
SelectList(s('#sex')).select_by_text('male')

simple and obvious
no any hidden magic:)


нд, 5 бер. 2017 о 13:09 Serhii Pirohov <notifications@github.com> пише:

**Comment by SergeyPirogov** [comment]
Arguments make sense
