### ISSUE TITLE
Selene Selenium 3.0 Actions error

### ISSUE THREAD

**Issue by SergeyPirogov** [yashaka/selene#113]
According to new release of GeckoDriver https://github.com/mozilla/geckodriver/releases
and new version of selenium python binding == 3.3.0 Selene will fail in **SeleneElement.__init()__** method
This is due to ActionChains, seems that new version of binding brings key that says if a given browser is w3c compliant. 

During debug I found that to fix this issue we need to init ActrionChains like this:

```
 self._actions_chains = ActionChains(webdriver._source.driver)
```
instead of:

```
self._actions_chains = ActionChains(webdriver)
```

**Comment by yashaka** [comment]
Hm... that's weird...

That means that somehow SeleneDriver does not implement WebDriver interface
fully...

Need to dig deeper into this...

But so far we can release a patch with temporal fix, if this blocks
somebody...

**Comment by SergeyPirogov** [comment]
Well I think we need to make a Selenium 3.0 branch and test it

**Comment by yashaka** [comment]
ok, let's do this...

**Comment by kylefix** [comment]
Don't you just need to add the following to abctypes/webdriver.py?

`    @abstractproperty
    def w3c(self):
        # todo: bool
        pass
`

**Comment by daveenguyen** [comment]
I am playing with a `selenium-3.5.0` branch.

https://travis-ci.org/daveenguyen/selene/builds/273968339

I have 2 tests failing on travis.
I was wondering anybody had any thoughts.
They look timing related.

2.7
```
______________________________ test_waits_nothing ______________________________
tests/integration/filtered_scollection_nowaiting_search_test.py:51: in test_waits_nothing
    assert len(elements) == 2
E   assert 1 == 2
E    +  where 1 = len(<selene.elements.__len__ object at 0x7f67f83c9790>)
==================== 1 failed, 136 passed in 360.85 seconds ====================
```

3.5
```
________ test_selene_is_from_32_to_65_percents_slower_than_raw_selenium ________
tests/acceptance/speed_comparison_of_simple_element_actions_test.py:80: in test_selene_is_from_32_to_65_percents_slower_than_raw_selenium
    assert selene_time <= 1.65 * selenium_time
E   assert 0.5911405086517334 <= (1.65 * 0.3450355529785156)
==================== 1 failed, 136 passed in 320.60 seconds ====================
```

**Comment by evgenynalivayko** [comment]
I ran into this problem. But I do not see the 
"@abstractproperty
def w3c(self): 
    # type: () -> bool
    pass"
 in the "abctypes/webdriver.py" file. 
If it is already removed, it did not work.

**Comment by evgenynalivayko** [comment]
where do you propose to use this  @kylefix ?

**Comment by evgenynalivayko** [comment]
I understood
Need to add to the file abctypes/webdriver.py

this

`@abstractproperty
def w3c(self): 
    # type: () -> bool
    pass`

Everything works!

**Comment by yashaka** [comment]
Seems like was fixed in the past...
And for sure is not relevant in 2.*
