### ISSUE TITLE
New driver  instance starts when trying to switch to alert

### ISSUE THREAD

**Issue by zaitsevmaxim80** [yashaka/selene#117]
Hi all!
I am using pre-release version of selene: 1.0.0.a10
I got an error when i was trying to switch to alert.
Here is a script to reproduce:

`
from selene.browser import driver, visit
from selene.support.jquery_style_selectors import s
from selene import config
from selene.browsers import Browser

config.browser_name = Browser.CHROME

visit('http://javascript.ru/alert')
s('input[value="Запустить"]').click()
alert = driver().switch_to.alert  # Current driver instance has been closed and new driver  instance is starting
alert.accept() # so we get an exception at the last step: selenium.common.exceptions.NoAlertPresentException: Message: no alert open
`

**Comment by yashaka** [comment]
Hi, can you please check the same case for raw selenium?

I am curious where the real problem lies...

**Comment by SergeyPirogov** [comment]
Hmmm, it's veeery interesting, probably we should add unit test for this.

**Comment by yashaka** [comment]
We should:) But I am interested whether the raw selenium will work in this
case:) It may also fail... :)

сб, 25 бер. 2017 о 17:06 Serhii Pirohov <notifications@github.com> пише:

**Comment by zaitsevmaxim80** [comment]
The same case for raw selenium is OK, no errors:

`
from selenium import webdriver

driver = webdriver.Chrome(executable_path=r"C:\\_Tools\\chromedriver.exe")
driver.get('http://javascript.ru/alert')
driver.find_element_by_css_selector('input[value="Запустить"]').click()
alert = driver.switch_to.alert
alert.accept()
`

**Comment by yashaka** [comment]
ok, great:-) Let's fix Selene then:-)

**Comment by SergeyPirogov** [comment]
@zaitsevmaxim80 could you please clarify which python version do you use? Seems this problem relates to v2 vs v3 string unicode =(

**Comment by zaitsevmaxim80** [comment]
I am using
Python 3.5.3
32-bit

**Comment by SergeyPirogov** [comment]
Thank you. I already identified the problem.

**Comment by SergeyPirogov** [comment]
Fixed by https://github.com/yashaka/selene/pull/118
