### ISSUE TITLE
If by.xpath contains utf8 symbols and not condition get UnicodeEncodeError: 'ascii'

### ISSUE THREAD

**Issue by kixiro** [yashaka/selene#124]
<pre>
Checking for linux geckodriver:v0.14.0 in cache
Driver found in /home/toxa/.wdm/geckodriver/v0.14.0/geckodriver
Traceback (most recent call last):
  File "./first_step.py", line 21, in <module>
    s(by.xpath("//button[contains(.,'Объекты')]")).should_be(be.conditions.Clickable()).click()
  File "/usr/local/lib/python2.7/dist-packages/selene/elements.py", line 305, in should
    _wait_with_screenshot(self._webdriver, self, condition, timeout)
  File "/usr/local/lib/python2.7/dist-packages/selene/elements.py", line 187, in _wait_with_screenshot
    return wait_for(entity, condition, timeout, polling)
  File "/usr/local/lib/python2.7/dist-packages/selene/wait.py", line 17, in wait_for
    reason_string = '{name}: {message}'.format(name=reason.__class__.__name__, message=reason_message)
UnicodeEncodeError: 'ascii' codec can't encode characters in position 47-53: ordinal not in range(128)
</pre>

**Comment by SergeyPirogov** [comment]
Which version of python do you use?

**Comment by kixiro** [comment]
python 2.7.12

**Comment by SergeyPirogov** [comment]
try to user it like 

s(by.xpath("//button[contains(.,u'Объекты')]"))

**Comment by kixiro** [comment]
Object will not be found
<pre>
s(by.xpath("//button[contains(.,u'Объекты')]"))
</pre>
It's work:
<pre>
s(by.xpath("//button[contains(.,'Объекты')]"))
</pre>
but object is not found, get UnicodeEncodeError
I resolved it this way:
<pre>
diff --git a/selene/wait.py b/selene/wait.py
index afc5e69..a9e9f3d 100644
--- a/selene/wait.py
+++ b/selene/wait.py
@@ -14,6 +14,8 @@ def wait_for(entity, condition, timeout=4, polling=0.1):
             reason_message = getattr(reason, 'msg',
                                      getattr(reason, 'message',
                                              getattr(reason, 'args', '')))
+            if isinstance(reason_message, unicode):
+                reason_message = reason_message.encode('unicode-escape')
             reason_string = '{name}: {message}'.format(name=reason.__class__.__name__, message=reason_message)
             screen = getattr(reason, 'screen', None)
             stacktrace = getattr(reason, 'stacktrace', None)
</pre>

**Comment by SergeyPirogov** [comment]
could you please create PR for this

**Comment by SergeyPirogov** [comment]
https://github.com/yashaka/selene/pull/130
