### ISSUE TITLE
collection validation cause error

### ISSUE THREAD

**Issue by SergeyPirogov** [yashaka/selene#134]
ss("table > tr").should(have.text("3")) causes starange error 

```
reason: AttributeError: ("'__len__' object has no attribute 'get_actual_webelement'",)
```

**Comment by SergeyPirogov** [comment]
Actually, there is no difference between have.exact_texts and have.texts for collection

**Comment by yashaka** [comment]
There should be the difference... have.texts - should compare texts by
"contains"...

The original error - may really be weird, and we can consider to find the
way to improve the message...

But... that code ss("table > tr").should(have.text("3")) is incorrect...
have.text - is a "element condition" not a "collection condition"... so it
should not work nevertheless...



сб, 3 черв. 2017 о 03:58 Serhii Pirohov <notifications@github.com> пише:
