### ISSUE TITLE
No ability to get page url

### ISSUE THREAD

**Issue by SergeyPirogov** [yashaka/selene#15]
For example I want to check page url:

main_page = LoginPage().open().login("admin","admin")

main_page.url.should_be("blablabla")

I didn't found the way in selene to get current page Url. Maybe we need to add such method

**Comment by yashaka** [comment]
hm, will add soon) hope till the end of the week...

**Comment by SergeyPirogov** [comment]
I propose to add conditions for page url, sometimes it become useful to check page url. So I thonk we need to add such code:

```
class ExactPageUrl(WebDriverCondition):
    def __init__(self, text):
        self.expected = text

    def fn(self, webdriver):
        actual = webdriver.current_url
        if not self.expected == actual:
            raise ConditionMismatchException(
                expected=self.expected,
                actual=actual)


exact_page_url = ExactPageUrl
```
So user will be able to write such code `wait_to(page_url("http://localhost:8080/login"))`

**Comment by yashaka** [comment]
of course we need to add both page_url and exact_page_url :-)

I just am not sure whether we need the "page" word in the names...

**Comment by SergeyPirogov** [comment]
@yashaka Yeah, I wanted to clarify this moment and add this, because we faced with such gap on one of our projects

**Comment by SergeyPirogov** [comment]
https://github.com/yashaka/selene/pull/88

**Comment by yashaka** [comment]
Speaking about the issue subject...

Currently we can get the page url by get_driver().current_url
the same applies to title: get_driver().title

and so the question comes: Should we add direct helpers like: selene.tools.title() and selene.tools.current_url()
?

Selenide has this...

**Comment by SergeyPirogov** [comment]
I think we should add this two methods, just to keep user using selene methods instead of selenium
