### ISSUE TITLE
Elements overlapping : Element is not clickable at point. Other element would receive the click

### ISSUE THREAD

**Issue by f4hrenh9it** [yashaka/selene#16]
Hello, dear yashaka!

I have an issue with clicking on some elements, which overlapping by others in Chrome:

selenium.common.exceptions.WebDriverException: Message: unknown error: Element is not clickable at point (885, 403). Other element would receive the click: <iframe title="Каталог государственных сайтов" scrolling="no" frameborder="0" allowtransparency="0" style="background: none 0px 0px repeat scroll transparent !important; border: 0px !important; border-radius: 0px !important; bottom: 0px !important; box-shadow: none !important; box-sizing: content-box !important; cursor: auto !important; float: none !important; margin: 0px !important; max-height: none !important; max-width: none !important; min-height: 0px !important; min-width: 0px !important; opacity: 1 !important; overflow: hidden !important; outline: none !important; padding: 0px !important; right: auto !important; transform: none !important; visibility: visible !important; zoom: normal !important; top: 0px !important; left: 0px !important; height: 638px !important; width: 1025px !important; position: absolute !important; z-index: 2147473647 !important;"></iframe>
  (Session info: chrome=54.0.2840.59)
  (Driver info: chromedriver=2.23.414176 (4eb5bd96518311cc565323e59f08c6cfc140dcae),platform=Linux 4.2.0-35-generic x86_64)

In our testing framework we are using action chains a lot, to click directly in point of element:

actions().move_to_element_with_offset(to_element=element, xoffset=xoffset, yoffset=yoffset).click().perform()

And that's work good, and stable in Chrome 54 and FF 48.

Is it good idea to implement more methods in SElement using action chains, to give precise control over element actions? Or is it an issue of not assuring any condition?

Here some minimal working environment to catch error:
https://gist.github.com/lulunevermind/ac8e829fa5394ee3b899df7b743d3bd1

**Comment by yashaka** [comment]
Hi lulunevermind,

> Is it good idea to implement more methods in SElement using action chains, to give precise control over element actions?

How then would it look like?

like this:
```
s("#element").click_with_offset(xoffset=xoffset, yoffset=yoffset)
```
?

I am not pretty sure if this will be ok to create so much different SElement methods reflection different "actions chain" combination...

So far, it seems to me, that better just to create helper methods in each specific case to use it like this:

```
click_with_offset(s("#element", xoffset=xoffset, yoffset=yoffset)
```

What do you think?

**Comment by lulunevermind** [comment]
Hello, time.sleep(1) helps in this problem, so it's an issue of waiting.
I'll try to investigate further, maybe try to add waits in waits for ng, jQuery used in example site.
