### ISSUE TITLE
Add w3c attribute to selene.driver._shared_driver instance

### ISSUE THREAD

**Issue by Igur007** [yashaka/selene#162]
ActionChains  in selenium/webdriver/common/action_chains.py needs driver in __init__, and this driver must have w3c attribute, because of such usages: "if self._driver.w3c:"

In selene/elements.py:243: in __init__   an instance of ActionChains is created (self._actions_chains = ActionChains(webdriver) ), and webdriver is passed, but this instance of webdriver doesn't have an w3c attribute, and for instance "AttributeError: 'forward' object has no attribute 'w3c' " occurs.

Please, consider this issue.

In my case I extended IWebDriver (selene/abctypes/webdriver.py) class with this method, and it helped, but I'm not sure, that it's correct solution:
    @abstractmethod
    def w3c(self):
        pass

**Comment by SergeyPirogov** [comment]
@Igur007 We already have such PR https://github.com/yashaka/selene/pull/145. Will merge it than and will check result
