### ISSUE TITLE
condition be.in_dom always return True even for non-existing elements

### ISSUE THREAD

**Issue by ibalagurov** [yashaka/selene#163]
selene==1.0.0a11 version

**for existing element:**
```
browser.open_url('https://google.com')
existing_element = s('[name="q"]')
is_matched(condition=be.in_dom, webelement=existing_element)
```
=> True

try to get an selenium element:
```
existing_element.__delegate__
```

=> <selenium.webdriver.remote.webelement.WebElement (session="5c310ab3ba111cab146de85cd057de74", element="0.5933519601066488-1")>

and it's ok

**but for non-existing:**
```
browser.open_url('https://google.com')
unexisting_element = s('[name="ololo"]')
is_matched(condition=be.in_dom, webelement=unexisting_element)
```

**=> True but should be False!**

try to get an selenium element:
`unexisting_element.__delegate__`
Traceback (most recent call last):
File "<stdin>", line 1, in <module>
File "/usr/local/lib/python3.6/site-packages/selene/elements.py", line 199, in delegate
return self._locator.find()
File "/usr/local/lib/python3.6/site-packages/selene/elements.py", line 44, in find
return self._search_context.find_element(*self._by)
File "/usr/local/lib/python3.6/site-packages/selene/driver.py", line 89, in find_element
return self._webdriver.find_element(by, value)
File "/usr/local/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 744, in find_element
{'using': by, 'value': value})['value']
File "/usr/local/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 233, in execute
self.error_handler.check_response(response)
File "/usr/local/lib/python3.6/site-packages/selenium/webdriver/remote/errorhandler.py", line 194, in check_response
raise exception_class(message, screen, stacktrace)
**selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"css selector","selector":"[name="ololo"]"}**
(Session info: chrome=63.0.3239.108)
(Driver info: chromedriver=2.34.522932 (4140ab217e1ca1bec0c4b4d1b148f3361eb3a03e),platform=Mac OS X 10.13.2 x86_64)

**Comment by SergeyPirogov** [comment]
@ibalagurov I don't know where did you get is_matched. In selene we have 
```
s("locator").should(exists)
```

**Comment by ibalagurov** [comment]
@SergeyPirogov 
from selene.conditions import is_matched

it is the same as condition.match with swallowing exceptions

**Comment by SergeyPirogov** [comment]
@ibalagurov I've checked this code

```
s('[name="ololo"]').should(exist)
```
works fine and it's recommended way to assert element state. is_matched has a bug and always return True

**Comment by SergeyPirogov** [comment]
is_matched() takes two parameters. First is the condition and the second is the web element, but not is SeleneElement. So the right call will be

```
browser.open_url('https://google.com')
unexisting_element = s('[name="ololo"]')
is_matched(condition=be.in_dom, webelement=unexisting_element.get_actual_webelement())
```
