### ISSUE TITLE
Add options to browser config

### ISSUE THREAD

**Issue by vchudikov** [yashaka/selene#180]
Chrome options are always reseted when start chrome in factory.py
```
def __start_chrome():
    options = webdriver.ChromeOptions()
```
Much better would be an ability to set it in config

config.py
`chrome_options = None`

factory.py
```
def __start_chrome():
    options = webdriver.ChromeOptions() if config.chrome_options is None else config.chrome_options
```

**Comment by aleksandr-kotlyar** [comment]
`selene.support.shared.browser.config` needs browser `options` field

Example:
```python
from selene.support shared import browser
from selenium.webdriver import ChromeOptions

options = ChromeOptions()
options.binary_location = "/Applications/Brave\ Browser.app/Contents/MacOS/Brave\ Browser"

browser.config.browser_name = 'brave'
browser.config.options = options
```
without path to binary this is a simple google chrome launch instead of Brave browser launch

we need options in shared browser config to configure our browsers and tests well.

P.S. current selene version 2.0.0b5
