### ISSUE TITLE
Pycharm + pytest + selene = INTERNALERROR

### ISSUE THREAD

**Issue by maxim-zaitsev** [yashaka/selene#182]
Hi all!
I get an internal error when i start test via Pycharm 2018.2 and pytest-3.10.0
The first test is success but the second one  causes the error.
When i do the same via command line - no errors

code for reproduce: 

```python 
from selene.api import *


def setup_function(module):
    driver = webdriver.Chrome()
    browser.set_driver(driver)


def teardown_function(module):
    browser.quit()


def test_selene():
    browser.open_url('http://ya.ru')
    s('#text').set('Python Selene try 1')
    s('[type="submit"]').click()


def test_selene_2():
    browser.open_url('http://ya.ru')
    s('#text').set('Python Selene try 2')
    s('[type="submit"]').click()
```

Traceback in attached file
[traceback.txt](https://github.com/yashaka/selene/files/2561542/traceback.txt)

Same issue:
https://automated-testing.info/t/pycharm-pytest-selene-internalerror/21791/1
http://software-testing.ru/forum/index.php?/topic/36059-python-selene-pytest-pycharm-internalerror-pri-zapuske-testov/

**Comment by AvataCrawlings** [comment]
Not a selene error

**Comment by ibalagurov** [comment]
It looks like the Pycharm internal error, try to use a console directly

**Comment by maxim-zaitsev** [comment]
> It looks like the Pycharm internal error, try to use a console directly

I thought so too. But the same code without selene does not cause the error:

`
from selenium import webdriver

def setup_function(module):
    global driver
    driver = webdriver.Chrome()


def teardown_function(module):
    driver.quit()


def test_selene():
    driver.get('http://ya.ru')
    driver.find_element_by_id('text').send_keys('Python Selene try 1')
    driver.find_element_by_css_selector('[type="submit"]').click()


def test_selene_2():
    driver.get('http://ya.ru')
    driver.find_element_by_id('text').send_keys('Python Selene try 2')
    driver.find_element_by_css_selector('[type="submit"]').click()
`

**Comment by akaars** [comment]
I'm not sure this is important, but this behavior reproduced also on Linux and Mac

**Comment by ibalagurov** [comment]
Did you try to run Selene code example through the console?

**Comment by ibalagurov** [comment]
IMO it's not a selene issue

**Comment by maxim-zaitsev** [comment]
I think this is a compatibility bug of the current version of selene with the latest version of PyCharm.
PyCharm 2015 did not cause the error.

**Comment by akaars** [comment]
> As i wrote before:
> When i do the same via command line - no errors

Same for me

**Comment by alexzoo** [comment]
same for me

**Comment by ibalagurov** [comment]
Why are you ask here? 
Pycharm is IDE **for** python code. Python is not the language **for** Pycharm. Do you see the difference?
The code works without IDE. So the code is correct, but Pycharm isn't...
You just misunderstand what does mean Compatibility. Because in that particular case Python (and correct python programs) is the standard.

**Comment by KozhevnikovSergey** [comment]
@maxim-zaitsev 
Did you solve this problem?

**Comment by maxim-zaitsev** [comment]
> @maxim-zaitsev
> Did you solve this problem?

no,  I didn't :(

**Comment by SergeyPirogov** [comment]
This projec is not supported guys

**Comment by maxim-zaitsev** [comment]
> This projec is not supported guys

nice news :)

**Comment by maxim-zaitsev** [comment]
Сергей, может знаешь, кто-нибудь взялся за развитие проекта ?

**Comment by SergeyPirogov** [comment]
Не знаю таких людей.

**Comment by maxim-zaitsev** [comment]
> @maxim-zaitsev ^^

Игорь, а ты ?

**Comment by ibalagurov** [comment]
Не в курсе

**Comment by KozhevnikovSergey** [comment]
> 
> 
> This projec is not supported guys

Selene теперь не поддерживается?

**Comment by SergeyPirogov** [comment]
Мной точно нет

**Comment by akaars** [comment]
тоись светлая память? Жаль... :/

**Comment by SergeyPirogov** [comment]
@akaars может быть да, а может и нет :)

**Comment by ivdunin** [comment]
@maxim-zaitsev @KozhevnikovSergey JFYI в PyCharm 2019.1.1 JetBrains исправили эту проблему.

**Comment by maxim-zaitsev** [comment]
> @maxim-zaitsev @KozhevnikovSergey JFYI в PyCharm 2019.1.1 JetBrains исправили эту проблему.

Ура! Обновился до 2019.1.1. Проблема ушла.
Все спасибо за участие.

**Comment by ibalagurov** [comment]
а все потому что это проблема не Selene... вот это новость! =)

**Comment by aleksandr-kotlyar** [comment]
Jetbrains has fixed Pycharm :) Let's close the issue?

**Comment by maxim-zaitsev** [comment]
Closed.
