### ISSUE TITLE
DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated, and in 3.8 it will stop working     from collections import Sequence

### ISSUE THREAD

**Issue by boriskrutskih** [yashaka/selene#186]
Hi all. 

When I run this code, i have an error 

` from selene.browser import open_url

def open():
    open_url("http://google.com/") `

 **DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated, and in 3.8 it will stop working
    from collections import Sequence**

Python 3.7.2
Pytest 4.3.0
Selene 1.0.0a13
https://i.imgur.com/0tbE5bp.png

**Comment by ibalagurov** [comment]
There is the fix:
https://github.com/yashaka/selene/pull/187
@SergeyPirogov
