### ISSUE TITLE
consider moving to poetry from pipenv

### ISSUE THREAD

**Issue by yashaka** [yashaka/selene#189]
https://poetry.eustace.io/

**Comment by aleksandr-kotlyar** [comment]
https://python-poetry.org/

**Comment by aleksandr-kotlyar** [comment]
# TODO
1. Add poetry to project
2. Move dependencies to pyproject.toml
3. Update README and update CONTRIBUTING about poetry usage to contribute to selene.

**Comment by aleksandr-kotlyar** [comment]
To not overwrite all the arguments to poetry: https://github.com/samuelcolvin/pydantic/issues/314
The most interesting comment: https://github.com/samuelcolvin/pydantic/issues/314#issuecomment-441724139

**Comment by aleksandr-kotlyar** [comment]
Resolved in #302
