### ISSUE TITLE
ensure alerts work and covered in tests

### ISSUE THREAD

**Issue by yashaka** [yashaka/selene#190]

**Comment by aleksandr-kotlyar** [comment]
Hi, it seems to be done at #237 and needs a review.
I resurrected alert tests in 8b53e719c632ab308401bf52a3745c9f7cbd698c in case of #203 
And have ensured that alerts are working.

**Comment by aleksandr-kotlyar** [comment]
PR #237 is merged. 
@yashaka  Do we need more tests than we already have here [browser__switch_to__alert_test.py](https://github.com/yashaka/selene/blob/43dd6a763d9130707a7a0570c70e1cc6941268da/tests/integration/browser__switch_to__alert_test.py)? 
Or this issue can be closed as done?

**Comment by aleksandr-kotlyar** [comment]
If it's already full covered i prefer to close this old issue. We have new one #248 alert functionality issue which is not implemented yet and it's need to be covered after implementation, but for if current alert methods are covered - we should close current issue.

**Comment by aleksandr-kotlyar** [comment]
I checked codecov reports and discovered that method `switch_to()` is totally covered.
https://codecov.io/gh/yashaka/selene/src/master/selene/core/entity.py
![image](https://user-images.githubusercontent.com/17043964/103740762-e9f46300-5008-11eb-8391-443ab72bc69a.png)


And it's covered so much - also with selenium methods, and now is time to think about moving these tests from integration to acceptance category.

```python
def test_can_accept_alert(session_browser):
    session_browser.open(start_page)

    session_browser.element("#alert_btn").click()
    session_browser.switch_to.alert.accept()

    try:
        session_browser.switch_to.alert.accept()
        assert False, 'actual: alert presents, expected: alert not present'
    except NoAlertPresentException:
        assert True


def test_can_dismiss_confirm_dialog(session_browser):
    session_browser.open(start_page)

    session_browser.element("#alert_btn").click()
    session_browser.switch_to.alert.dismiss()

    try:
        session_browser.switch_to.alert.accept()
        assert False, 'actual: alert presents, expected: alert not present'
    except NoAlertPresentException:
        assert True


def test_alert_is_present(session_browser):
    session_browser.open(start_page)

    session_browser.element("#alert_btn").click()

    try:
        session_browser.switch_to.alert.accept()
        assert True
    except NoAlertPresentException:
        assert False, 'actual: alert not present, expected: alert is present'
```
