### ISSUE TITLE
SeleneCollection - Should Have Texts - Match Question

### ISSUE THREAD

**Issue by tooolya** [yashaka/selene#191]
Hi,

I'm trying to assert that there is some text in search result (SeleneCollection):

```python
""" For example, there is search result page with 3 items:

search_results = ['Lobster food', 'lobster film', 'lobster smobster']
"""
search_for = ['Lobster']
ss('some css selector').should(have.texts(search_for))
```

Code above fails with 

> reason: ConditionMismatchException: condition did not match

I have looked into [Texts class](https://github.com/yashaka/selene/blob/master/selene/conditions.py#L308) and found that there is length check between expected and actual texts in 'if' statement. 

> len(actual) == len(self.expected)

Am I not using Collection Conditions correctly? I mean, is it expected to have the same number of expected and actual texts?

**Comment by yashaka** [comment]
Hi @tooolya, 
`have.texts` asserts the exact number of items. If a search by selector results in a collection of 3 elements, then the `should` with `have.text` condition will pass only if you pass as expected - the collection with 3 items too...

**Comment by tooolya** [comment]
Hi @yashaka, 

I have misunderstood the purpose of `have.texts` (thought it would search in all elements by text or texts), thanks for quick response.  I'll just iterate over collection for my case.
