### ISSUE TITLE
Allure report test status

### ISSUE THREAD

**Issue by maxim-zaitsev** [yashaka/selene#192]
Allure marks test which has ended with unexpected exception (is not instance of AssertionError) as BROKEN.
So when I do checks via selene,  I get yellow marked test when it's failed, but logically it should be red marked test.

Example to reproduce:

```python
import allure
from selene.api import browser, s, ss, be, by, have


class TestTodoMVC(object):

    def test_allure_broken_status(self):
        browser.open_url('https://todomvc4tasj.herokuapp.com')
        with allure.step('New todo should not be blank (selene check)'):
            s("#new-todo").should_not(be.blank)

    def test_allure_failed_status(self):
        browser.open_url('https://todomvc4tasj.herokuapp.com')
        with allure.step('New todo should not be blank (python check)'):
            assert s("#new-todo").get_attribute('value') != ''
'''

**Comment by kydbakep** [comment]
Do you know any way to attach screenshots, created by selene, to allure report?

**Comment by aleksandr-kotlyar** [comment]
### Check 
Hi, @maxim-zaitsev i checked your tests on the current versions:
```ini
selene==2.0.34a
pytest==5.3.2,
allure-pytest==2.8.29 
```
First test passed and second failed. I made first to fail to by selene condition mismatch too.
```python
import allure
from selene.api import browser, s, be


class TestTodoMVC(object):

    def test_allure_broken_status(self):
        browser.open_url('https://todomvc4tasj.herokuapp.com')
        with allure.step('New todo should not be blank (selene check)'):
            s("#new-todo").should(be.not_.visible)  # <------- changed assertion

    def test_allure_failed_status(self):
        browser.open_url('https://todomvc4tasj.herokuapp.com')
        with allure.step('New todo should not be blank (python check)'):
            assert s("#new-todo").get_attribute('value') != ''

```
Allure-result: both tests `FAIL` (not `BROKEN`)

![image](https://user-images.githubusercontent.com/17043964/103448695-432d6100-4cae-11eb-992b-bfe4798005ca.png)


### Suggestion 

It's could be temporary bug of `allure-pytest`, not `selene`.

### Resolution
No matter what it was - it seems to have been already resolved.

@maxim-zaitsev if you still can reproduce the problem, please provide new example with details and library versions.

**Comment by maxim-zaitsev** [comment]
Yeah, this issue was fixed in version 2.
