### ISSUE TITLE
How to use shared driver with --headless arg?

### ISSUE THREAD

**Issue by albobrov** [yashaka/selene#200]
Hi!
I can't pass --headless arg to shared driver config.
SharedConfig source(chrome driver created with default options):
`new = {
            'chrome': lambda: Chrome(executable_path=ChromeDriverManager().install(),
                                     options=ChromeOptions()),
            'firefox': lambda: Firefox(executable_path=GeckoDriverManager().install())
        }.get(self.browser_name)()`

What's the best way to add args?

**Comment by yashaka** [comment]
```python
from selene.support.shared import browser
from selenium import webdriver

options = webdriver.ChromeOptions()
options.headless = True
browser.config.driver = webdriver.Chrome(chrome_options=options)

browser.open('http://todomvc.com/examples/emberjs/')
```

or

```python
from selene.support.shared import browser, config
from selenium import webdriver

options = webdriver.ChromeOptions()
options.headless = True
config.driver = webdriver.Chrome(chrome_options=options)

browser.open('http://todomvc.com/examples/emberjs/')
```

;)

**Comment by yashaka** [comment]
if you need, you can also provide executable_path from webdriver manager too...

**Comment by albobrov** [comment]
Thank you
