### ISSUE TITLE
Port old tests to selene v2.x

### ISSUE THREAD

**Issue by aleksandr-kotlyar** [yashaka/selene#203]
# Problem
Hello! I have noticed, here are two packages with tests at [master now](https://github.com/yashaka/selene/tree/aff2e07ff2f89a9e7f2c8239c42e3678a5c0e321) 
`tests` and `tests_from_past`
- ❗️ `tests_from_past` package tests don't work in current version 2.x 
```bash
E   ModuleNotFoundError: No module named 'selene.api.past' 
```
- ❗️ `tests` package has very few tests
# Question
What's the plan for testing selene now? Does selene 2.x needs to be covered or not yet?
# Answer
For sure it needs to be covered. The plan is to migrate tests from past to the new version.
# Plan
Contains from two stages:
1. Copying one by one from tests_from_past/integration to tests/integration folder and making them pass.
2. Take into account corresponding tests from selenidejs at https://github.com/KnowledgeExpert/selenidejs/tree/master/test/integration
Compare and add missing tests.
# Workflow for contributors who want to help
1. Choose module or pack of modules from `tests_from_past.integration` package.
2. Write them down here in comment to this issue, that you start to work at their migration to `tests.integration` and write the suggestion date you will finish (count +week/2weeks/month from start). We will count on you till this date.
3. Fork the project.
4. Install dependencies. 
5. Use latest 2.X version (now it's 2.0.0a21).
6. Mention this issue as "#203" in your commits.
7. Pull master before making your PR and resolve conflicts locally.

**Comment by yashaka** [comment]
For sure it needs to be covered. The plan is to migrate tests from past to the new version.

Copying one by one from tests_from_past/integration to tests/integration folder and making them pass.

It's also good to take into account corresponding tests from selenidejs at https://github.com/KnowledgeExpert/selenidejs/tree/master/test/integration

You are welcome to start a new PR;)
