### ISSUE TITLE
module 'selene.browser' has no attribute 'open'

### ISSUE THREAD

**Issue by joshglenn** [yashaka/selene#209]
Running this code on Python 3.8.2 64-bit for WIndows:

```py
from selene import browser
browser.open('https://google.com/ncr')
```

I get the following error:

```
Exception has occurred: AttributeError
module 'selene.browser' has no attribute 'open'
```

Any idea why?

**Comment by joshglenn** [comment]
The code I was using must be for an older version (straight from this project's README.md), because when I ran `browser.open_url` it worked just fine.

```py
from selene import browser
browser.open_url('https://google.com/ncr')
```

**Comment by yashaka** [comment]
@joshglenn 
It might have another reason too... 

Even if you use latest alpha version 2.0.0a*, the selene.browser module is deprecated
It actually contains old methods from Selene <= 1.0

If you want to use "shared automatic driver management" you should import like this:

```python
from selene.support.shared import browser
browser.open('https://google.com/ncr')
```

... as described in the readme:

![image](https://user-images.githubusercontent.com/1961118/79542571-8f8b2f00-8094-11ea-8339-d7c933fdf762.png)


If you want to use your own browser management, you do like this:

![image](https://user-images.githubusercontent.com/1961118/79542639-aaf63a00-8094-11ea-8f4a-fb6cb6012c27.png)
