### ISSUE TITLE
len(elements) doesn't work

### ISSUE THREAD

**Issue by esterity** [yashaka/selene#215]
Selene version 2.0.0a18 -> 2.0.0a28
There're 10 elements in actions

![image](https://user-images.githubusercontent.com/34091210/82570008-b05e0d00-9b89-11ea-9b40-071f7a2952e0.png)

**Comment by yashaka** [comment]
@esterity, are you sure?

I don't see an issue on my side... Can you share more details? maybe try to reproduce the issue on some public site, or give access to your one...

**Comment by esterity** [comment]
I’ll try to reproduce it on public site

**Comment by esterity** [comment]
I couldn't reproduce on google.com :(
I also tried to add a 1-second pause after browser.all and elements were counted correctly in my project.
Idk how elements are cached in Selene, maybe the page loads slowly so elements aren't fully cached.

**Comment by yashaka** [comment]
Elements aren't cached if you don't do that explicitly by calling .cached

I mean each time you do something with element or collection - it takes the
actual version of elements from the page. Selene and no any other tool
based on Selenium webdriver can't implicitly wait for your page elements to
fully load on a page. Selene can implicitly wait for visibility of exactly
1 element that you specified. Implicit waiting for more than one element is
kind of impossible in general case becaouse nobody except you knows how
many elements in collection should appear on the page. You should specify
exact condition for that explicitly

**Comment by esterity** [comment]
Thanks for your explanation
