### ISSUE TITLE
Loading files into an element in a state of invisibility

### ISSUE THREAD

**Issue by timosmon** [yashaka/selene#217]
I would like to see the ability to upload files to an element, even if it is hidden. I cant use Selene`s send_keys and set_value cause it is work only with visible condition of elements. Thank you!

**Comment by yashaka** [comment]
try the `browser.element(selector).type(keys)` method from 2.0.0-alpha* releases... it should work as a normal selenium send_keys... 

I will think also about whether to add the "raw" send_keys for that or not...

**Comment by timosmon** [comment]
It is works, thanks!
