### ISSUE TITLE
document migrating pytest ini selene properties from 1.0 to 2.0 where pytest ini was removed

### ISSUE THREAD

**Issue by yashaka** [yashaka/selene#222]

**Comment by aleksandr-kotlyar** [comment]
I checked
0.0.8
1.0.0a8
1.0.0a13
1.0.0a16
1.0.1
1.0.2
and din't find any pytest.ini file

@yashaka can you please provide the link to `pytest.ini` file commit which need to be migrated?

**Comment by yashaka** [comment]
Actually I don't remember what was this issue about...

But probably the idea was the following.

Selene 1.0 supported customizing shared browser config through pytest.ini file in real user projects.
But in Selene 2.0 we remove this support completely. 
So we have to document somehow what users should do in such case. 
Like exact steps during migration.

**Comment by aleksandr-kotlyar** [comment]
Need an example of this `pytest.ini` file.  🙂

**Comment by yashaka** [comment]
I don't have it)
We have to do a research. I just feel that I saw such examples in the past,
and filed this issue to not forget to manage this.
I would check how settings are managed in 1.0 and find some ideas there...
maybe ask in our chat ...

**Comment by yashaka** [comment]
ok then... let's close it...
