### ISSUE TITLE
[tests] add negative tests for collection conditions `have.text`, `have.texts`. (from pr-review #237)

### ISSUE THREAD

**Issue by aleksandr-kotlyar** [yashaka/selene#250]
Test-Cases to write in module:
`tests/integration/condition__collection__have_texts_test.py`

- [ ] have.text throw Exception
- [ ] have.texts throws Exception
- [ ] have.no.text pass
- [ ] have no.texts pass
- [ ] have no.text throws Exception
- [ ] have no.texts throws Exception

**Comment by kianku** [comment]
I'm taking this task. will text you when finished.

**Comment by kianku** [comment]
- [ ] have.text throw Exception
- [ ]  have.texts throws Exception
- [ ]  have.no.text pass
- [x]  have no.texts pass
- [ ]  have no.text throws Exception
- [ ]  have no.texts throws Exception
