### ISSUE TITLE
break setup.py's dependencies into two versions: for python 2 and 3

### ISSUE THREAD

**Issue by yashaka** [yashaka/selene#26]
currently it looks like: 
install_requires=['selenium==2.53.1', 'future', 'backports.functools_lru_cache'],

but when using python 3, you don't need e.g. backports.functools_lru_cache

**Comment by yashaka** [comment]
Hm... but I am unsure whether we need it or not...

**Comment by SergeyPirogov** [comment]
Close because we don't need it anymore
