### ISSUE TITLE
ModuleNotFoundError: No module named 'selene.support.shared'

### ISSUE THREAD

**Issue by sugizo** [yashaka/selene#285]
**code**
`from selene.support.shared import browser`
**result**
```
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-2-3e2da90ace3c> in <module>
----> 1 from selene.support.shared import browser

ModuleNotFoundError: No module named 'selene.support.shared'
```
**version**
```
selene-1.0.2
```

**Comment by aleksandr-kotlyar** [comment]
That's true. There is no `shared` directory inside `selene.support` in `selene-1.0.2`. 
Try `from selene import browser`.
@sugizo Does it work for you?

**Comment by sugizo** [comment]
its written in 
https://github.com/yashaka/selene/blob/master/README.md

**objective**
to test selene for newbie user

**question**
what is correct syntax for quick start working code in selene ?

thanks

**Comment by aleksandr-kotlyar** [comment]
> its written in
> https://github.com/yashaka/selene/blob/master/README.md

Yes. But it's also has a link to readme for [1.x](https://github.com/yashaka/selene/tree/1.x ) versions:
![image](https://user-images.githubusercontent.com/17043964/109387121-7d168e80-7910-11eb-8905-28189acadb87.png)

You can find the actual readme there. Am I answered your question?

**Comment by sugizo** [comment]
yes you right, my bad read wrong manual, thx
for 1.0.2 version should be
`from selene import browser`
