### ISSUE TITLE
update webdriver-manager to latest version

### ISSUE THREAD

**Issue by yashaka** [yashaka/selene#299]
current:
<img width="950" alt="image" src="https://user-images.githubusercontent.com/1961118/112041686-5a624900-8b4f-11eb-9d59-b4e286c65bc1.png">
while: 
<img width="628" alt="image" src="https://user-images.githubusercontent.com/1961118/112041761-6d751900-8b4f-11eb-8075-5f026cd41f00.png">

**Comment by EmadDeve20** [comment]
#300

**Comment by EmadDeve20** [comment]
Hi @yashaka !
I'm trying to update this model with tips @aleksandr-kotlyar in the #301!

what is my wrong?
![Screenshot from 2021-04-13 13-04-08](https://user-images.githubusercontent.com/60766355/114522849-fb2cbb80-9c58-11eb-8b9c-31990148ceca.png)

**Comment by aleksandr-kotlyar** [comment]
> Hi @yashaka !
> I'm trying to update this model with tips @aleksandr-kotlyar in the #301!
> 
> what is my wrong?
> ![Screenshot from 2021-04-13 13-04-08](https://user-images.githubusercontent.com/60766355/114522849-fb2cbb80-9c58-11eb-8b9c-31990148ceca.png)

Because poetry see version 2.3.0 in pyproject.toml and tells that there is nothing to update.
You should change webdriver-manager version in pyproject.toml before.

**Comment by EmadDeve20** [comment]
#318

**Comment by a-karro** [comment]
Just a comment: since selene has been moved to poetry, and poetry is super strict on versions, I would suggest to use "minimum version" pattern for better compatibility. Instead of "version": "==strict.version" I think it would be better to use ">=minimal.version". 
(at the moment I'm waiting for the next release of selene because pyshadow has listed their webdriver as >=2.5.3, and selene with its currently required 2.3.0 is _no bueno_)

**Comment by aleksandr-kotlyar** [comment]
Hi @a-karro! Thank you for your comment! I really appreciate it. But I want to correct your statements.
Not only poetry is super strict on versions, it can be requirements.txt or Pipfile, it is a conscious decision of developers to control versions on which they have tested their product and what they support for now.

Also you shouldn't wait for a new version of selene - you can use any dependency resolver which support few versions of sub-dependencies like poetry.

We will release new version of selene soon.

**Comment by aleksandr-kotlyar** [comment]
@a-karro selene [2.0.0a37](https://github.com/yashaka/selene/releases/tag/2.0.0a37) with webdriver-manager 3.3.0 has been released!  😉 
Also selene [2.0.0a38](https://github.com/yashaka/selene/releases/tag/2.0.0a38) with webdriver-manager 3.4.1 has been released yesterday.
Thank you for using selene! 🙂
