### ISSUE TITLE
Make a smart scrolling to the element

### ISSUE THREAD

**Issue by extsoft** [yashaka/selene#3]
If you switch between screen resolutions (13' and 23' etc.), some tests may fail because an element is visible for 23' and isn't visible for 13'. So, as one of way to handle this, we can try to catch errors with invisible elements and try to scroll to them.

**Comment by yashaka** [comment]
we definitely need something like `SElement#scroll_to_self`... 
good idea to think also about "smart scrolling"...

**Comment by SergeyPirogov** [comment]
scroll_to added
