### ISSUE TITLE
Document mentioning issue number in commit messega for contributed PR 

### ISSUE THREAD

**Issue by yashaka** [yashaka/selene#311]
Now we have:
<img width="877" alt="image" src="https://user-images.githubusercontent.com/1961118/114300906-07830e00-9acb-11eb-8e6a-c88e11a06cf8.png">

```
Commit your changes (git commit -am 'Add some feature')
```
but should have something like:

```
Commit your changes (`git commit -am "$ISSUE_NUMBER: Add some feature"`, where ISSUE_NUMBER is the number of issue this commit relates to)

```

Additional todos:
- emphasize that -am is just an example, for sure we should use `git add ...` if new files were added - reflect this somehow in contribution guide also

**Comment by aleksandr-kotlyar** [comment]
One improvement: `git commit -am "gh_$ISSUE_NUMBER: Add some feature"` for example: `gh_311` in commit message will link a commit to the issue.

**Comment by yashaka** [comment]
do we really need this `gh_` prefix? all the time it worked with `#` prefix for me:) It's shorter) and kind of more intuitive

**Comment by aleksandr-kotlyar** [comment]
When you will want to refactor commit history with squash or something - it will be hard to pick commits starts with `#` cause it means 'commented' raw 🙂 . I had some troubles with it.

**Comment by yashaka** [comment]
Ah... Ok, let's stick to gh_ then!

**Comment by aleksandr-kotlyar** [comment]
I was wrong: to link commit to PR need to use `#num` for example `gh_#311` to link
