### ISSUE TITLE
refactor timeouts in givenpage.py to be seconds based, not ms based

### ISSUE THREAD

**Issue by yashaka** [yashaka/selene#312]
Check this test:
```
    browser = session_browser.with_(timeout=0.5)
    page = GivenPage(browser.driver)
    page.load_body_with_timeout(
        '''
        <a href="#second">go to Heading 2</a>
        <h2 id="second">Heading 2</h2>       
        ''',
        250,
    )
```
in first line we use timeout in seconds, in pre-pre-last - in ms - INCONSISTENCY!!! :)

Let's fix it:)
Let's refactor timeouts in givenpage.py to be seconds based, not ms based. 
And adapt all tests correspondingly.

**Comment by Vikilib** [comment]
I will do
