### ISSUE TITLE
support latest versions of selenium

### ISSUE THREAD

**Issue by yashaka** [yashaka/selene#32]

**Comment by daveenguyen** [comment]
I am playing with a `selenium-3.5.0` branch.

https://travis-ci.org/daveenguyen/selene/builds/273968339

I have 2 tests failing on travis.
I was wondering anybody had any thoughts.
They look timing related.

2.7
```
______________________________ test_waits_nothing ______________________________
tests/integration/filtered_scollection_nowaiting_search_test.py:51: in test_waits_nothing
    assert len(elements) == 2
E   assert 1 == 2
E    +  where 1 = len(<selene.elements.__len__ object at 0x7f67f83c9790>)
==================== 1 failed, 136 passed in 360.85 seconds ====================
```

3.5
```
________ test_selene_is_from_32_to_65_percents_slower_than_raw_selenium ________
tests/acceptance/speed_comparison_of_simple_element_actions_test.py:80: in test_selene_is_from_32_to_65_percents_slower_than_raw_selenium
    assert selene_time <= 1.65 * selenium_time
E   assert 0.5911405086517334 <= (1.65 * 0.3450355529785156)
==================== 1 failed, 136 passed in 320.60 seconds ====================
```

**Comment by SergeyPirogov** [comment]
There is an appropriate PR for Selenium 3. All tests are green, but still, it's better to stay with selenium 2.51.0

**Comment by daveenguyen** [comment]
@SergeyPirogov all tests are green, but if you look at the log the tests actually installed **selenium 2.53.1**

**Comment by SergeyPirogov** [comment]
@daveenguyen yes, exactly

**Comment by aleksandr-kotlyar** [comment]
Seems its a stale issue. Latest selenium 3.141.59 already supported by `selene 1.0.1` and new `selene 2.0.0a34`. I think it can be closed.
