### ISSUE TITLE
Unclear part of description in "Migration guide" block 

### ISSUE THREAD

**Issue by dimien** [yashaka/selene#366]
![image](https://user-images.githubusercontent.com/8645636/125139063-80b8ee00-e118-11eb-9b8c-065df676feb7.png)
Duplicated text in the description leads to unclear context. 

"example:
find&replace all
(text('foo')) to (have.text('foo'))
**(be.visible) to (be.visible)**"

**Comment by yashaka** [comment]
Hm, seems like should be `(visible) to (be.visible)`
