### ISSUE TITLE
Release new version to enable new webdriver-manager that fixes core functionality on Windows

### ISSUE THREAD

**Issue by alkuzad** [yashaka/selene#367]
Without it selene can't run tests on Firefox cause it won't start.

**Comment by yashaka** [comment]
Uh!
we'll try to fix this asap!

**Comment by yashaka** [comment]
@alkuzad, done!
https://pypi.org/project/selene/2.0.0a39/

**Comment by alkuzad** [comment]
normally it wouldn't be a problem but with poetry ... I managed to hack it using git dependencies instead of pypi but I'm glad you released new version fast :) It's common problem in OpenSource that not every merge == new release and ones that seem not important get lost in the limbo
