### ISSUE TITLE
how to connect gird

### ISSUE THREAD

**Issue by ycwdaaaa** [yashaka/selene#376]
I did not found the config with config.remote to set the grid hub address like in selenide.  Do I have any way to do that?

**Comment by yashaka** [comment]
Right now, you don't have a config for that, if you need to set your tests to run remotely, you have to create the instance of WebDriver on your own and pass it to the Selenide, like this: 

```python
from selene.support.shared import browser
myDriver = ...
browser.config.driver = myDriver
```

Check the full example here: https://github.com/yashaka/python-web-test/blob/b8d4ab9d68aa8fb8e6b5323cfcb6d32b5dcce3e0/tests/conftest.py#L52

P.S. 
We may add the same option like in Selenide, but still thinking on the best way to do this...
