### ISSUE TITLE
selene.core.entity import webdriver from android - is a typo?

### ISSUE THREAD

**Issue by aleksandr-kotlyar** [yashaka/selene#398]
@yashaka i have found a possible typo in selene.core.entity imports:

https://github.com/yashaka/selene/blob/14e05c5a3e9e7a91832bfc1af5dd950e9c67a147/selene/core/entity.py#L36

i think it should be
```python
from selenium.webdriver.remote.webdriver import WebDriver
```
What do you think?

**Comment by yashaka** [comment]
@aleksandr-kotlyar, yes, looks like a typo... please, fix, run tests and if everything is fine we are ready to go:)
