### ISSUE TITLE
Add ability to set up custom time of waiting for element loading

### ISSUE THREAD

**Issue by extsoft** [yashaka/selene#4]
Before make any action with element, selene waits for `config.timeout` seconds to load an element. But it's possible that for some elements need to set up other timeout. For example, some ADJX request is very slow and `config.timeout` is not enough. 
It can be implemented as:
`s(".css", load_during=15)` or
`s(".csss"). load_during(15)` or anything like this.
Finally, this means selene will wait up to specified time before make some action.

**Comment by SergeyPirogov** [comment]
implemented as s("locatos").wait_until(condition, time)
