### ISSUE TITLE
Set a style property value via Selene

### ISSUE THREAD

**Issue by amitaz3354** [yashaka/selene#412]
Hey, I need to change and style property value of a slider element inside my HTML.
`<div class="slide-yada-yada" role="slider" aria-valuemin="0" aria-valuemax="1000" aria-valuenow="0" tabindex="0" style="left: 0%;"></div>`

How can I do it via selene ? :)

Thanks a lot !

**Comment by yashaka** [comment]
Hm.. how would you do it with selenium we driver?

I then prepare a receipt for Selene...

**Comment by maxim-zaitsev** [comment]
Look at this example:

```python
from selene.api import browser, s

my_element = s('locator')
new_style_value = 'right: 100500%;'
browser.execute_script('arguments[0].setAttribute("style",arguments[1])', my_element(), new_style_value)
```

**Comment by yashaka** [comment]
This will also work:

```
from selene.api import browser, s

new_style_value = 'right: 100500%;'
s('locator').execute_script('element.setAttribute("style",arguments[0])', new_style_value)
```

Maybe we also can add an extra command to allow user something like:

```
from selene.api import browser, s, command

s('locator').perform(command.js.set_style('right: 100500%;'))
```

**Comment by yashaka** [comment]
Added:

```
from selene.api import browser, s, command

s('locator').perform(command.js.set_style_property('right', '100500%'))
```
