### ISSUE TITLE
Docs for Selene? :D

### ISSUE THREAD

**Issue by yashaka** [yashaka/selene#456]
I don't like docs:) I mean... I like products that are obvious to use, and documentation is built as docstrings in the code (where needed) and fits perfectly into README.md

Unfortunately... For some reason:D, The world likes "shiny docs" :)... Probably, at least of PR reasons, we should add some pretty looking website with docs to Selene... :) 

Let's consider some options... Taking into account that we already have some outdated docs mentioned in #122

**Comment by yashaka** [comment]
I actually liked such implementation: https://github.com/grammyjs/website -> https://grammy.dev

**Comment by yashaka** [comment]
Cypress docs are also known as one of the best:) 
https://github.com/cypress-io/cypress-documentation -> https://docs.cypress.io/

**Comment by yashaka** [comment]
Any good example of something «pythonic»? ;)

**Comment by hotenov** [comment]
@yashaka I love documentation :)

I think, more  «pythonic» will be using Read the Docs (with Sphinx) or GitHub pages (with Jekyll by default).

I use Read The Docs. It's possible to choose any visual theme and customize it. Also Sphinx extensions let you auto generate reference pages from docstrings in the code.

**Sorry for self promotion** :) This is my docs website https://lep-downloader.readthedocs.io/  
with auto-generated reference (developer) documentation page with all classes, methods, etc  
https://lep-downloader.readthedocs.io/en/latest/reference.html

I can help to set up if you need or even make a PR :)

**Comment by yashaka** [comment]
@hotenov 
Hm... Probably you are right... we should use something like read the docs (we already used it in the past)... 

Let's choose the theme:) Can we find something similar to grammy.dev with corresponding colors/fonts? 
<img width="1727" alt="image" src="https://user-images.githubusercontent.com/1961118/197501562-f61acab4-4585-45fa-a996-cd4032ab5812.png">


In meantime I will try to collect "requirements"... The first one would be 
* at least to have search by https://www.algolia.com/, that looks like: 
<img width="1235" alt="image" src="https://user-images.githubusercontent.com/1961118/197501416-b48558ac-d610-4d9a-bb97-463fa8ee4253.png">

**Comment by yashaka** [comment]
If Github Pages [is something "more shiny"](https://t.me/selene_py_ru/6933), let's use it ;)

**Comment by MatuMikey** [comment]
The best pythonic docs I have ever witnessed myself personally can be attributed to FastAPI. It is the most comprehensive and well explained docs out there in my opinion.

https://fastapi.tiangolo.com/

**Comment by hotenov** [comment]
> https://fastapi.tiangolo.com/

agree, and they use (it seems) [Material Design theme](https://bashtage.github.io/sphinx-material/) which is widely used by other developers.

When I was chosing theme for my project, it was on 2nd place. But [Furo theme](https://github.com/pradyunsg/furo) with automatic dark theme won :)

**Comment by yashaka** [comment]
@MatuMikey, Heh))) Thanks of an example) Let's do for Selene the same: https://fastapi.tiangolo.com/

**Comment by hotenov** [comment]
Some notes for future docs improvements / theme customizations

## Material theme

MkDocs and this theme let you change almost any UI aspect,  
overrideing certain parts or even the whole HTML template(s).

As I understtod, it's very flexible (especially if you know HTML and JS).

Related links:  
https://squidfunk.github.io/mkdocs-material/customization/#overriding-blocks  
https://www.mkdocs.org/user-guide/customizing-your-theme/

Besides that, theme has a wide range of [configuration options](https://squidfunk.github.io/mkdocs-material/creating-your-site/#advanced-configuration),  
which let you change some UI elements without front-end skills.

Discovered minor issues with material theme

- Inserting docstrings from class with many attributes (more than 12)  
  (methods, subclusses, etc.) breaks scroll over ToC (right panel) after 12th list item
- Toggle function (dark / light) does not work in Mozilla mobile browser 

## Writing docs

Related links:  
https://www.mkdocs.org/user-guide/writing-your-docs/

MkDocs supports basic Markdown syntax and has a lot of markadown extensions,  
if you need more specific functionality.

Out-the-box (built-in) support of [Fenced code blocks](https://www.mkdocs.org/user-guide/writing-your-docs/#fenced-code-blocks) (Stackoverflow or GitHub style)

After merging linked PR it will be possible to install only docs dependencies  
on your local machine (without installing unnecessary stuff for docs editors,  
including selene itself :)

For that simply do this:
- Pull changes / clone repo
- `poetry install --only docs`
- `poetry shell`
- `mkdocs serve`
- Open URL in browser `http://127.0.0.1:8000/selene/
- Edit and save docs files, local server will watch for changes

Suggestion: Integrate code-style for docs files too  

- Strongly recommend writers / editors to use Markdown linters in their IDE
- Define one style for lists items, emphasizing text, code blocks etc.
- Maybe add MD linters for docs in CI/CD or command (script) in the future  
  who doesn't use IDE

**Comment by hotenov** [comment]
@yashaka I think, Selene documentation is not a joke anymore :-D ☝

Here's it -> https://yashaka.github.io/selene/

For linking other issues, you can find it by search and you can close it now.
