### ISSUE TITLE
Dependencies: webdriver-manager: please consider upgrading to 3.8.4 (Apple M1 and chromedriver naming changes)

### ISSUE THREAD

**Issue by a-karro** [yashaka/selene#457]
Google in their infinite wisdom decided to change their chromedriver naming scheme for Apple M1. Starting from "106.0.5249.61" they're postfixing the driver name with "_arm64" instead of previously used "_m1".

Webdriver-manager 3.8.3 and earlier still tries to use the old scheme, and the driver download fails. [Webdriver-manager 3.8.4](https://github.com/SergeyPirogov/webdriver_manager/blob/master/webdriver_manager/drivers/chrome.py) takes care of this, but 3.8.3 is a hard dependence for selene, and can't be changed easily (or, in other words, I don't know how to tame poetry dependencies).

Please consider bumping the webdriver-manager version to 3.8.4.

**Comment by MatuMikey** [comment]
@yashaka I made a PR to fix this issue here

**Comment by yashaka** [comment]
fixed in b15 or b16
