### ISSUE TITLE
Create style guide for DOCS files, Consider documentation structure

### ISSUE THREAD

**Issue by hotenov** [yashaka/selene#459]
Refer comments to PR https://github.com/yashaka/selene/pull/458 and issue #456 for start

**Comment by hotenov** [comment]
## Docs questionnaire to project owner @yashaka 

where 👍 - my personal preference (but no pressure ;)

| # | Area | Question | Options |
|---|:---:|---|---|
| 1 | layout | Where to store (put) images for individual page? | a) 👍 Always put into sub-folder `images` where .md file is located  <br>b) Store images without sub-folder along with .md files in this folder  <br>c) Store images in one global folder (i.e. theme folder `assets/images` or separate global folder for docs images `assets/images-docs`  <br>d) Provide other option  |
| 2 | layout | How docs will be organized? Pay attention that folders and filename are URL paths on website| a) Provide folders (URLs) structure  <br>b) Provide types of documents which will be written (faq, guides, tutorials, internals, etc.)  <br>see my current mind's eye -> [draft example](https://hotenov.github.io/selene-with-docs/contrib/docs/how-to-organize-docs/#selene-docs-structure) |
| 3 | layout | How to name .md files? | a) 👍 Use hyphen(s) in lower case filenames  <br>b) User underscore(s) in lower case filenames  <br>c) Arbitrary name (with spaces and random case)   |
| 4 | nav | How navigation menu (left on the website) will be structured? | a) Provide structure with section / sub-section / page headers  <br>look at current [draft implementation](https://hotenov.github.io/selene-with-docs/) (left menu) |
| 5 | syntax | Links: Will we insist on using reference links (instead of inline links)?  <br>i.e. [click me][selene-github]  <br>[selene-github]: https://yashaka.github.io/selene/ | a) 👍 Yes  <br>b) No |
| 6 | syntax | Links: What format will we use for reference text in links? | a) 👍 Lower case words separated by hyphens, i.e. `[click me][selene-github]`  <br>b) Lower case words separated by spaces, i.e. `[click me][selene github]`<br>c) No matter (arbitrary text, including UPPER case)  <br>d) Provide other option |
| 7 | syntax | Links: What order will be in reference list? | a) Alphabetical order  <br>b) 👍 Order of appearance in text  <br>c) No matter (arbitrary order)  <br>d) Provide other option |
| 8 | syntax | Code blocks: How to write language identifier in fenced blocks? | a) 👍 Without space after three back-ticks  <br>b) With space  <br>b) No matter |
| 9 | content | Should I provide syntax example on our page for such standard blocks as:  <br>Footnotes, Tables, Blockquotes, Inline HTML  <br>if there is a link to cheat sheet with standard syntax  <br>(see [draft](https://hotenov.github.io/selene-with-docs/contrib/docs/how-to-write-docs/) page)  | a) 👍 No, link to cheat sheet will be enough<br>b) Yes, long-read in one place is better |
| 10 | content | Should I provide syntax example on our page for fancy theme's blocks  <br>(Admonitions, Content tabs, Buttons, etc.)  <br>or simply add link to material theme reference page. | a) Yes, will be nice to have long-read with all fancy examples  <br>b) 👍 No, link to theme page will be enough,<br>because some blocks might be required setup in configuration file<br>(not configured during initial docs setup, i.e. what we are doing now) |
| 11 | UI | Should I enable theme feature `content.tabs.link` for tabbed content?  <br>Current state is disabled,<br>You can click on tabs on [draft page](https://hotenov.github.io/selene-with-docs/contrib/docs/how-to-write-docs/#emphasis) <br>(each tab is switched individually) | a) Enable - this means that all tabs with the same label will be activated<br>when a user clicks a content tab regardless of order inside a container.  <br>b) 👍 Disable - each tab switched individually |
| 12 | git | Will we use special branch name pattern for docs contributions?  <br>for example, `docs-*` or `docs/*`  <br>This let us to trigger Markdown linter (or other docs CI job)<br>only for such branches.<br>Also we can add PR auto-labeler (in the future)<br>to assign label for PR from docs branches  | a) 👍 Yes, and pattern will be `docs-*`  <br>b) Yes, and pattern will be `docs/*`  <br>c) No, pattern is no needed<br>d) Yes, but provide other pattern |
| 13 | github | Need we add separate issue label<br>for documentation tasks?   | a) 👍 Yes, I will add `docs` label  <br>b) Yes, I will add label with another title  <br>c) No, we don't needed it now |
| 14 | linter | There is an option to add GitHub action with linting Markdown files,  <br>to check standard syntax,  <br>but it will require one more config file `markdownlint.conf` in  <br>root of the project and additional discussion about its setup.  <br>Need we this linter now? or delay its integration,  <br>when MD syntax becomes a real problem and we integrate `pre-commit` hooks<br>for Markdown linting | a) Yes, let's integrate it now as quick way<br>b) Create issue for the future<br>c) We no need it, local (IDE) linter will be enough  <br>d) 👍 It's better to integrate `pre-commit` hooks in the future |
| 15 | website optimization | Should we insist writers / editors to provide optimized images? (shrink size via external services) | a) 👍 Yes, they should care about website performance  <br>b) No, it's too much for editors. |


## What **I've already changed**  
(without your approving) on [draft docs website](https://hotenov.github.io/selene-with-docs/):  

- I divided CONTRIBUTING.md on three pages:
    - "How to contribute" - it's snippet of modified CONTRIBUTING.md in the root located in /contrib/code/how-to-contribute/
    - "Code Conventions" - it's new page in /contrib/code/code-conventions/
    - "Release workflow" - it's new page in /contrib/code/release-workflow/  
    Pay attention that I renamed it (was "Release process")
- I converted all links (except all badges links) in README.md to reference links
- I formatted README.md according to draft rules. Also I removed "dollar" character ($) from installation commands (because Markdown linter require output line for these commands)
- I inserted links to docs website for CONTRIBUTING.md, "Release workflow" and "CHANGELOG.md" links at the end of README.md, i.e. visitors from GitHub or PyPI will be redirected to docs website (not GitHub).
- I changed case to lower for pages which includes pages with CAPS LOCK, in order URL will be in lowe case (It's mor common), for example will be https://yashaka.github.io/selene/changelog/
- I changed GitHub repo icon to "cat" because it's more associated with GitHub than Git icon
- I added "social" links to the footer (from README)  
   ![image](https://user-images.githubusercontent.com/11818507/199456999-85fe51cf-b12a-4cf2-b368-d2f7f3e1e430.png)

**Comment by yashaka** [comment]
1 :

assets is inside same directory where my-file.md lives.

```md
This is my-fild.md file content 
![](assets/my-pic.png)
```

2: need to think more on it...
not sure if like something like `/guide/how-to-integrate-selene-into-selenium-project.md` 
i would love more something like `/how-to-integrate-selene-into-selenium-project.guide.md`

3: a) 👍 Use hyphen(s) in lower case filenames 

I would add to the end the "type" sufix, i.e. guide in `/how-to-integrate-selene-into-selenium-project.guide.md`... but not sure... 

let's then try to use such sufixes (i.e. tags in names)

4: 
(below: ./ is the root of repo)

* Overview (-> ./README.md)
* Learn Basics
  * Selene Quick Start -> ./docs/learn-core/selene-quick-start.tutorial.md (https://yashaka.github.io/selene/learn-core/selene-quick-start-tutorial)
* Learn Advanced
  * Custom Selene Conditions
* FAQ
  * How to configure chrome with profile -> ./docs/faq/how-to-configure-chrome-with-profile.faq.md (https://yashaka.github.io/selene/faq/how-to-configure-chrome-with-profile-faq)
* Real Life Examples
  * 
* Contributing
  * ...
  * ...
* Changelog
* License

  
If the section is empty it can be omitted so far...

5: recommend reference links over full url links

6: a) 👍 Lower case words separated by hyphens, i.e. [click me][selene-github]

7: b) 👍 Order of appearance in text 

8: a) 👍 Without space after three back-ticks 

9: a) 👍 No, link to cheat sheet will be enough

10: b) 👍 No, link to theme page will be enough,
because some blocks might be required setup in configuration file

11: b) 👍 Disable - each tab switched individually

12: a) 👍 Yes, and pattern will be docs-*

13: a) 👍 Yes, I will add docs label 

14: d) 👍 It's better to integrate pre-commit hooks in the future

15: a) 👍 Yes, they should care about website performance

**Comment by yashaka** [comment]
> I divided CONTRIBUTING.md on three pages: 

Ok, just make it two-levels, i.e:

* Contributing (first level)
  * How to ... (second level)
  
...

And OK to everything else.

**Comment by hotenov** [comment]
Eventually, after discussion in private this navigation structure was approved:

```plain
Overview  # -> ./README.md
Learn Basics
    ...
Learn Advanced
    ...
FAQ
    ...
Use Cases
    ...
Contribution
    ...
Changelog
License
```

and folders (URLs) structure:

```plain
📁 docs/
├── 📁 assets
    ├── 📁 images
        ├── 🎨 logo-icon.png
        └── 🎨 favicon.png
├── 📁 contribution/
    ├── 📄 code-conventions.guide.md
    ├── 📄 index.md
    ├── 📄 ...
    └── 📄 to-source-code.guide.md
├── 📁 faq/
    ├── 📁 assets/
        └── 🎨 chrome-driver-window.png
    ├── 📄 index.md
    ├── 📄 q-tbd-1.howto.md
    └── 📄 custom-chrome-profile.howto.md
├── 📁 learn-advanced/
    ├── 📁 assets/
    ├── 📄 index.md
    ├── 📄 learn-deeper-1.tutorial.md
    └── 📄 learn-deeper-2.guide.md
├── 📁 learn-basics/
    ├── 📄 index.md
    ├── 📄 quick-start.tutorial.md
    └── 📄 learn-something.tutorial.md
├── 📁 use-cases/
    ├── 📁 assets/
        └── 🎨 my-pic.png
    ├── 📄 ex-tbd-1.example.md
    ├── 📄 ex-tbd-2.example.md
    └── 📄 index.md
├── 📄 changelog.md
├── 📄 index.md
└── 📄 license.md
```

**Comment by hotenov** [comment]
Documentation website was updated https://yashaka.github.io/  
with new structure and formatted README (Overview)
