### ISSUE TITLE
`be.selected` condition checks for attribute `elementIsSelected`?

### ISSUE THREAD

**Issue by dskard** [yashaka/selene#478]
It appears that the `be.selected` condition is checking if the element has an attribute named `elementIsSelected`. Should this be calling the Selenium function `is_selected()`, in the same way that the `be.enabled` condition calls `is_enabled()`?

Should this chunk:
https://github.com/yashaka/selene/blob/007ebe0c484418f78ef4ad7026620ccb2174c6f1/selene/core/match.py#L240-L242

look more like this:
```python
element_is_selected: Condition[Element] = ElementCondition.raise_if_not(
    'is selected', lambda element: element().is_selected()
)
```

**Comment by yashaka** [comment]
Heh, looks like yes, it should just call the corresponding selenium method.
You can create a PR if you want...

**Comment by dskard** [comment]
i'll add a pr soon.
