### ISSUE TITLE
migrate from webdriver-manager to official Selenium Manager

### ISSUE THREAD

**Issue by arturshevchenko** [yashaka/selene#494]
migrate to selenium 4.11 which allows manage drivers automatically

**Comment by yashaka** [comment]
@arturshevchenko, what do you mean? Can you explain the issue in more details? 

Currently the version of Selenium is not frozen in Selene, you can use whatever latest selenium version you want...

**Comment by yashaka** [comment]
Do you mean «Migrate from WebDriver Manager to Selenium Manager»?

Selenium Manager was available also in earlier versions, not just 4.11... The question is only - is it fully ready to substitute WebDriver Manager?

**Comment by arturshevchenko** [comment]
now, you manage web driver using selenium-manager(external dependency) . 
since 4.11 been released you can use directly native selenium manager -- which will handle web browser binaries and even browsers. 
check this https://www.selenium.dev/blog/2023/whats-new-in-selenium-manager-with-selenium-4.11.0/

**Comment by yashaka** [comment]
See my comment above)

**Comment by yashaka** [comment]
In general - all my hands for using official versions of webdriver managers, if they are available. My only concern is this part from the link you provided:

> [Selenium Manager](https://www.selenium.dev/documentation/selenium_manager/) **is still in beta**, although it is becoming a relevant component of Selenium.

**Comment by yashaka** [comment]
The killer feature of Selenium Manager is that it also downloads the browser (e.g. Chrome for Testing) not just driver...

But... Only Chrome browser is currently supported as "automatically downloadable".

Also I am not sure that even geckodriver is supported for case of Firefox...

![image](https://github.com/yashaka/selene/assets/1961118/0de85823-f0eb-451d-8e86-a97fa9358a52)

We can fully migrate only when at least chrome and firefox are fully supported in context of driver binaries... Probably Edge is also important for us...

**So here is where a help from the community needed - do an analysis and provide a proven list of what is supported and what is not – browser (Chrome, Firefox, Edge) per platform (Windows, MacOS, Linux)**

**Comment by yashaka** [comment]
will be released in 2.0.0rc6 soon ;)
