### ISSUE TITLE
Fix the DeprecationWarning message for save_page_source method

### ISSUE THREAD

**Issue by ksmyshlyaev** [yashaka/selene#495]
As of now, the method `save_page_source()` at the selene -> core -> entity.py:1249 is deprecated and the DeprecationWarning message says

> 'browser.save_page_source is deprecated, '
            'use browser.config.last_screenshot'
          
which is not relevant and might be confusing.
The suggestion is to change it to

> use browser.get(query.page_source_saved())

**Comment by yashaka** [comment]
go for it! waiting for PR
