### ISSUE TITLE
ModuleNotFoundError: No module named 'webdriver_manager.core.os' on v 2.0.0rc2

### ISSUE THREAD

**Issue by dimaklepikov** [yashaka/selene#499]
`selene/core/configuration.py` calls a non-existing module from WDM. 

This occurs on calling `browser.driver` imported from 'selene.api'

**Comment by yashaka** [comment]
Hey, the latest version is 2.0.0rc4, can you upgrade and check your case with it? Probably it will be fixed...

**Comment by dimaklepikov** [comment]
Thanks!
