### ISSUE TITLE
Find By alternative solution

### ISSUE THREAD

**Issue by extsoft** [yashaka/selene#5]
It's possible to use selenium's ```By.*``` instead on customs like ```s(locator, by=By.CSS)```. So, CSS is default. And if you have to use any other: ```s("//xpath", By.XPATH)```.
Also it's possible to make something like that: ```s(xpath("//xpath"))```.

**Comment by yashaka** [comment]
already implemented in more "straightforward" and imho "concise" way:

```python
s(by_xpath("//xpath"))
```

this is also the same API that Selenide supports now :)
