### ISSUE TITLE
Automatic driver management , need  config to install and setup driver for local

### ISSUE THREAD

**Issue by zhupengfarmer** [yashaka/selene#501]
ERR selenium.common.exceptions.WebDriverException: Message: unknown error: cannot find Chrome binary

jenkins:
testcase/cc/callside/WorkbenchSMS_Test.py::Test_pyt::test_py 
testcase/cc/callside/CustomTabPageCheck_Test.py::Test_pyt::test_py 
testcase/cc/calltype/InCall_Test.py::Test_pyt::test_py 
[WDM] - Downloading:   0%|          | 0.00/639 [00:00<?, ?B/s]
[WDM] - Downloading: 8.67kB [00:00, 37.2MB/s]                 

[WDM] - Downloading:   0%|          | 0.00/639 [00:00<?, ?B/s]
[WDM] - Downloading: 8.67kB [00:00, 39.6MB/s]                 

[WDM] - Downloading:   0%|          | 0.00/639 [00:00<?, ?B/s]
[WDM] - Downloading: 8.67kB [00:00, 39.4MB/s]                 

[gw1] [ 12%] RERUN testcase/cc/callside/WorkbenchSMS_Test.py::Test_pyt::test_py 
testcase/cc/callside/WorkbenchSMS_Test.py::Test_pyt::test_py 
[gw0] [ 25%] RERUN testcase/cc/callside/CustomTabPageCheck_Test.py::Test_pyt::test_py 
testcase/cc/callside/CustomTabPageCheck_Test.py::Test_pyt::test_py 
[gw2] [ 37%] RERUN testcase/cc/calltype/InCall_Test.py::Test_pyt::test_py 
testcase/cc/calltype/InCall_Test.py::Test_pyt::test_py 
[WDM] - Downloading:   0%|          | 0.00/639 [00:00<?, ?B/s]
[WDM] - Downloading: 8.67kB [00:00, 34.1MB/s]                 

[WDM] - Downloading:   0%|          | 0.00/639 [00:00<?, ?B/s]
[WDM] - Downloading: 8.67kB [00:00, 34.7MB/s]                 

[gw1] [ 37%] RERUN testcase/cc/callside/WorkbenchSMS_Test.py::Test_pyt::test_py 
testcase/cc/callside/WorkbenchSMS_Test.py::Test_pyt::test_py 
[WDM] - Downloading:   0%|          | 0.00/639 [00:00<?, ?B/s]
[WDM] - Downloading: 8.67kB [00:00, 35.1MB/s]                 

[gw2] [ 37%] RERUN testcase/cc/calltype/InCall_Test.py::Test_pyt::test_py 
testcase/cc/calltype/InCall_Test.py::Test_pyt::test_py 
[gw0] [ 37%] RERUN testcase/cc/callside/CustomTabPageCheck_Test.py::Test_pyt::test_py 
testcase/cc/callside/CustomTabPageCheck_Test.py::Test_pyt::test_py 
[WDM] - Downloading:   0%|          | 0.00/639 [00:00<?, ?B/s]
[WDM] - Downloading: 8.67kB [00:00, 35.0MB/s]                 

[WDM] - Downloading:   0%|          | 0.00/639 [00:00<?, ?B/s]
[WDM] - Downloading: 8.67kB [00:00, 35.8MB/s]                 

[WDM] - Downloading:   0%|          | 0.00/639 [00:00<?, ?B/s]
[WDM] - Downloading: 8.67kB [00:00, 31.0MB/s]                 

**when run pytest ,always download driver.
need config to set local dierver version**

**Comment by yashaka** [comment]
@zhupengfarmer, Hey, sorry, I did not respond to your issue on time. Did you find the fix? What was it?

**Comment by zhupengfarmer** [comment]
@yashaka use selenoid it worked ,No more frequent downloads

**Comment by yashaka** [comment]
yeap, Selenoid is nevertheless the best choise in such scenarios...

In meantime, we will progress in the way of "removing dependency to webdriver_manager completelyt" so we don't have such issues in future...
