### ISSUE TITLE
add ability to specify config options via env variables

### ISSUE THREAD

**Issue by yashaka** [yashaka/selene#51]

**Comment by SergeyPirogov** [comment]
The solution might be like this http://stackoverflow.com/questions/36141024/how-to-pass-environment-variables-to-pytest

**Comment by SergeyPirogov** [comment]
Added in https://github.com/yashaka/selene/pull/96

User will be able to set config via ENV variables using two approaches:

1) Using CMD

```
selene_browser=chrome selene_hold_browser_open=True py.test  /tests
``` 

2) Using **pytest-env** plugin:
https://github.com/MobileDynasty/pytest-env

Just need to create pytest.ini file and set variables:

```
[pytest]
env=
      selene_browser=chrome
      selene_hold_brower_open=True
     ...
```

**Comment by yashaka** [comment]
How first option will look in windows cmd? :-)

**Comment by SergeyPirogov** [comment]
Did not get it? Any problems with Windows?

**Comment by yashaka** [comment]
I meant this:
http://superuser.com/questions/223104/setting-environment-variable-for-just-one-command-in-windows-cmd-exe

:)

пт, 17 лют. 2017 о 09:21 Serhii Pirohov <notifications@github.com> пише:
