### ISSUE TITLE
path of screenshot and pagesource on failure – should be windows friendly

### ISSUE THREAD

**Issue by yashaka** [yashaka/selene#519]
Currently the rendered in the error message path on Windows – is not clickable, because is rendered incorrectly... 
![telegram-cloud-photo-size-2-5440527300132198140-y](https://github.com/yashaka/selene/assets/1961118/a0677ff2-7715-4180-a8ef-10976f2a67fc)

**Comment by cshimm** [comment]
I am working on this.
