### ISSUE TITLE
clear default screenshot folder by default, and provide config. option to control this

### ISSUE THREAD

**Issue by yashaka** [yashaka/selene#52]

**Comment by yashaka** [comment]
Or maybe leave it as "false" by default... ? :)

**Comment by SergeyPirogov** [comment]
There is a place for discussion. 
Do we really need flag and write tricky logic for folder cleaning? Maybe we should provide clean_screenshots_folder() method and user will be able to call this function in some test fixture for example before_all tests?

**Comment by yashaka** [comment]
Seems like this is really impossible to do on our side... to implement something like `atexit`, but `atstart`. Then I don't see any sense in creating some custom helper that will clean the directory. User can create it by himself as he wishes.
