### ISSUE TITLE
bug: value_containing() missing 1 required positional argument: 'expected' in case of collections negating for each

### ISSUE THREAD

**Issue by roman-isakov** [yashaka/selene#547]
example:

`ss('collection').should(have._not_.attribute('name').value_containing('value').each)`
or
`ss('collection').should(have.no.attribute('name').value_containing('value').each)`

returns

`TypeError: attribute.<locals>.value_containing() missing 1 required positional argument: 'expected'`

without `no` works as expected, probably.

**Comment by yashaka** [comment]
Fixed in master and will be part of the next release
