### ISSUE TITLE
consider accepting more than one condition in should methods

### ISSUE THREAD

**Issue by yashaka** [yashaka/selene#61]

**Comment by aleksandr-kotlyar** [comment]
> consider accepting more than one condition in should methods #61

What is the use case? Why not stop on the chained `should().should()`? Chained `should` looks more obvious.

**Comment by yashaka** [comment]
`element.should(have.text("foo"), have.text("bar"))  # considered`
vs
`element.should(have.text("foo").and_(have.text("bar"))) # currently possible` 

so, the first version is kind of conciser and cleaner... 
but, ok, why not keep things simpler:) and more explicit:)

let's close this for now

**Comment by aleksandr-kotlyar** [comment]
> `element.should(have.text("foo"), have.text("bar")) # considered`
> vs
> `element.should(have.text("foo").and_(have.text("bar"))) # currently possible`
> 
> so, the first version is kind of conciser and cleaner...
> but, ok, why not keep things simpler:) and more explicit:)
> 
> let's close this for now

Agreed. Current version looks good. 🙂 

I want to add some thoughts in the end:
The first one version wouldn't be clear to users. 
> element.should(have.text("foo"), have.text("bar")) # considered
It makes questions:- is it `and` or `or` when conditions are separated inside should() by comma? 
If it's "and", then how to make them "or"? And so on.
It's interesting, but if to look forward: it will be hard to explain, to maintain and to test, and it will need something like `shoulld_any( , , )` to separate `"or"` logic through this kind of api from `"and"` logic of `should( , , )`
