### ISSUE TITLE
add selene.config.hold_browser_open (equal to false by default)

### ISSUE THREAD

**Issue by yashaka** [yashaka/selene#68]

**Comment by SergeyPirogov** [comment]
@yashaka why this feature can be useful? You want to add flag that will disable driver.quit in case of automatic driver management?

**Comment by yashaka** [comment]
yeah, disabling driver.quit

This feature is kind of "debug feature". Sometimes it is handy to see where
your test finished, when you are still in progress of developing a test.

I use it sometimes in case of java + selenide

**Comment by SergeyPirogov** [comment]
https://github.com/yashaka/selene/pull/83
