### ISSUE TITLE
add ability to disable webdriver_manager

### ISSUE THREAD

**Issue by SergeyPirogov** [yashaka/selene#70]
This is needed in case of errors and/or cases when tests are started in environment without direct acess to internet

**Comment by SergeyPirogov** [comment]
@yashaka Well I think we don't need to add any additional flags to control this, just need to say that users can disable automatic driver management just by setting their own driver using `set_driver()`

**Comment by yashaka** [comment]
we actually already say this in readme:)

but... maybe we need a way to "customize webdriver_manager", e.g. by
telling him which driver binary to use...

**Comment by SergeyPirogov** [comment]
It will be the same, there is no big difference between set_driver() with path to driver binary and **set_some_variable** with path to the driver executable. The only case is to say that user can load driver himself and put into cache folder, so driver_manager will use it

**Comment by SergeyPirogov** [comment]
I've released wd_manager version 1.4.

According to this issue we are able to disable wd_manager https://github.com/SergeyPirogov/webdriver_manager/issues/11

**Comment by yashaka** [comment]
Looks cool! Will add something to selene readme about this...
