### ISSUE TITLE
Wrong file separator in the path to screenshot (Win OS)

### ISSUE THREAD

**Issue by juliaviluhina** [yashaka/selene#71]
If a test was failed, an error message is included path to the screenshot
In Win OS, there is C:\Users\user/.selene/screenshots/1484762993605/screen_1484762993606.png

This screenshot is able to be opened through the browser, however, the path to screenshot includes different file separators.

It can confuse Selene users )

**Comment by SergeyPirogov** [comment]
Fixed by https://github.com/yashaka/selene/pull/72/files
