### ISSUE TITLE
How I can use unicode text conditions?

### ISSUE THREAD

**Issue by arturgspb** [yashaka/selene#9]
subj

**Comment by yashaka** [comment]
This have not been even tested yet... Seems like this is needed to be implemented... Will check...

**Comment by arturgspb** [comment]
I'm sorry, I'm beginner in python and not use "u" prefix when testing your library.
Now comment # -*- coding: utf-8 -*- with "u" prefix works fine.

**Comment by arturgspb** [comment]
@yashaka, look at library http://selenide.org/quick-start.html. I've been using it and its api is very good and very similar to yours, there is something to peep for selene!

**Comment by yashaka** [comment]
I have been using selenide for a long time:) And the absence of its
alternative in python make be create it by myself and name Selene.

So, Selene is actually a port of Selenide (and also html-elements) library
to python. Selene was inspired by it, and actually I am just copying all
features from it... ;)

On Sun, Dec 13, 2015 at 1:16 PM, Artur Geraschenko <notifications@github.com

**Comment by arturgspb** [comment]
Good news! I was looking for just the port of selenide.
