### ISSUE TITLE
selene.config.screenshot_folder vs selene.config.reports_folder

### ISSUE THREAD

**Issue by yashaka** [yashaka/selene#98]
we have selene.config.screenshot_folder
but selenide has:
```
  /**
   * Folder to store screenshots to.
   * Can be configured either programmatically or by system property "-Dselenide.reportsFolder=test-result/reports".
   *
   * Default value: "build/reports/tests" (this is default for Gradle projects)
   */
  public static String reportsFolder = System.getProperty("selenide.reportsFolder",
          System.getProperty("selenide.reports", "build/reports/tests"));
```

it made me think that in future we might have not only screeshots as reportable artifacts, but probably some other logs... 

should not we then rename screenshot_folder to reports_folder?

**Comment by SergeyPirogov** [comment]
yes, make sense to rename

**Comment by yashaka** [comment]
ok, let's do this

we just need to ensure that we still will have screenshots inside
$selene_reports_folder/screenshots

On Sun, Feb 26, 2017, 2:28 AM Serhii Pirohov <notifications@github.com>
wrote:

yes, make sense to rename

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/yashaka/selene/issues/98#issuecomment-282538636>, or mute
the thread
